[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
SpineInterface = "0cda1612-498a-11e9-3c92-77fa82595a4f"
SpineOpt = "0d8fc150-4032-4b6e-9540-20efcb304861"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
