name = "SpineOpt"
uuid = "0d8fc150-4032-4b6e-9540-20efcb304861"
authors = ["Spine Project consortium <spine_info@vtt.fi>"]
version = "0.5.3"

[deps]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Clp = "e2554f3b-3117-50c0-817c-e040a3ddf72d"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SpineInterface = "0cda1612-498a-11e9-3c92-77fa82595a4f"

[compat]
JuMP = "0.21.2"
SpineInterface = "0.5.7"
julia = "^1.2"
